---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: stop container
    command: sudo docker stop insurance
     
  - name: remove container
    command: sudo docker rm insurance

  - name: deploy insurance application
    command: sudo docker run -itd -p 8081:8081 --name insurance ashnike/insurance:1.0
